clouds:
  dev:
    environments:
      cspr:
        regions:
          westus3: 760831a01899e2599bfdb9ce3126c19d9777291b8963807015dee0cb40969daa
      dev:
        regions:
          westus3: 169451b5a6ef617fc1e651ffdcc5eaf753666e0bcdc345cf3c65197359e6fea6
      ntly:
        regions:
          uksouth: dfb0e1e82ba1ee6e7a48f9f43e89720b556d7eb1eac5cbe521151b59addc8b73
      perf:
        regions:
          westus3: 003d10777dc16ca15b1e0abf5ef1dff9af796496dfb2574b0f36f7289164f612
      pers:
        regions:
          westus3: f6674b0a78e3e7714a62441bd65e31c20a384b373d97355da364470632200696
      prow:
        regions:
          westus3: 7dca9a8c69a01c4aca99bb630dcde2570a0aaef7a9c7f84abb6cb091b52b79ee
      swft:
        regions:
          uksouth: 79e847d2a9076fd9cfc64d9cd521b6fcd7a99a940230f1cc4bca17b1839e82e2
